"""initial

Revision ID: 023b32cbca0a
Revises: 
Create Date: 2022-11-04 21:33:17.072734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023b32cbca0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rtpijobdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_info_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('filter', sa.Text(), nullable=True),
    sa.Column('offset', sa.BigInteger(), nullable=True),
    sa.Column('limit', sa.BigInteger(), nullable=True),
    sa.Column('taken', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rtpijobdata_id'), 'rtpijobdata', ['id'], unique=False)
    op.create_index(op.f('ix_rtpijobdata_taken'), 'rtpijobdata', ['taken'], unique=False)
    op.create_table('rtpijobinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=191), nullable=True),
    sa.Column('table_count', sa.BigInteger(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remained_count', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rtpijobinfo_id'), 'rtpijobinfo', ['id'], unique=False)
    op.create_index(op.f('ix_rtpijobinfo_table_name'), 'rtpijobinfo', ['table_name'], unique=False)
    op.create_table('rtpiprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('date_observe', sa.DateTime(), nullable=True),
    sa.Column('stock_status', sa.Text(), nullable=True),
    sa.Column('current_price', sa.BigInteger(), nullable=True),
    sa.Column('crossed_price', sa.BigInteger(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_price_id', 'date_observe', name='web_price_id_date_observe_unique')
    )
    op.create_index(op.f('ix_rtpiprice_id'), 'rtpiprice', ['id'], unique=False)
    op.create_index(op.f('ix_rtpiprice_stock_status'), 'rtpiprice', ['stock_status'], unique=False)
    op.create_index(op.f('ix_rtpiprice_web_price_id'), 'rtpiprice', ['web_price_id'], unique=False)
    op.create_table('rtpipricepage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('price_name', sa.Text(), nullable=True),
    sa.Column('price_url', sa.Text(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('date_last_in_stock', sa.DateTime(), nullable=True),
    sa.Column('rosstat_id', sa.Integer(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('date_last_crawl', sa.DateTime(), nullable=True),
    sa.Column('city_code', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_price_id', name='web_price_id_unique')
    )
    op.create_index(op.f('ix_rtpipricepage_id'), 'rtpipricepage', ['id'], unique=False)
    op.create_index(op.f('ix_rtpipricepage_web_price_id'), 'rtpipricepage', ['web_price_id'], unique=False)
    op.create_table('rtpiproductname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('moment', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_price_id', 'product_name', 'moment', name='web_price_id_product_name_moment_unique')
    )
    op.create_index(op.f('ix_rtpiproductname_id'), 'rtpiproductname', ['id'], unique=False)
    op.create_index(op.f('ix_rtpiproductname_web_price_id'), 'rtpiproductname', ['web_price_id'], unique=False)
    op.create_table('rtpistoreid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('store_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_name', name='store_name_unique')
    )
    op.create_index(op.f('ix_rtpistoreid_id'), 'rtpistoreid', ['id'], unique=False)
    op.create_index(op.f('ix_rtpistoreid_store_id'), 'rtpistoreid', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rtpistoreid_store_id'), table_name='rtpistoreid')
    op.drop_index(op.f('ix_rtpistoreid_id'), table_name='rtpistoreid')
    op.drop_table('rtpistoreid')
    op.drop_index(op.f('ix_rtpiproductname_web_price_id'), table_name='rtpiproductname')
    op.drop_index(op.f('ix_rtpiproductname_id'), table_name='rtpiproductname')
    op.drop_table('rtpiproductname')
    op.drop_index(op.f('ix_rtpipricepage_web_price_id'), table_name='rtpipricepage')
    op.drop_index(op.f('ix_rtpipricepage_id'), table_name='rtpipricepage')
    op.drop_table('rtpipricepage')
    op.drop_index(op.f('ix_rtpiprice_web_price_id'), table_name='rtpiprice')
    op.drop_index(op.f('ix_rtpiprice_stock_status'), table_name='rtpiprice')
    op.drop_index(op.f('ix_rtpiprice_id'), table_name='rtpiprice')
    op.drop_table('rtpiprice')
    op.drop_index(op.f('ix_rtpijobinfo_table_name'), table_name='rtpijobinfo')
    op.drop_index(op.f('ix_rtpijobinfo_id'), table_name='rtpijobinfo')
    op.drop_table('rtpijobinfo')
    op.drop_index(op.f('ix_rtpijobdata_taken'), table_name='rtpijobdata')
    op.drop_index(op.f('ix_rtpijobdata_id'), table_name='rtpijobdata')
    op.drop_table('rtpijobdata')
    # ### end Alembic commands ###
