"""tables without unique constr

Revision ID: 2eb4f937f770
Revises: 9a68c1d7c904
Create Date: 2022-09-05 16:26:42.226511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb4f937f770'
down_revision = '9a68c1d7c904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nu_rtpiprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('date_observe', sa.DateTime(), nullable=True),
    sa.Column('stock_status', sa.Text(), nullable=True),
    sa.Column('current_price', sa.BigInteger(), nullable=True),
    sa.Column('crossed_price', sa.BigInteger(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nu_rtpiprice_id'), 'nu_rtpiprice', ['id'], unique=False)
    op.create_index(op.f('ix_nu_rtpiprice_stock_status'), 'nu_rtpiprice', ['stock_status'], unique=False)
    op.create_index(op.f('ix_nu_rtpiprice_web_price_id'), 'nu_rtpiprice', ['web_price_id'], unique=False)
    op.create_table('nu_rtpipricepage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('price_name', sa.Text(), nullable=True),
    sa.Column('price_url', sa.Text(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('date_last_in_stock', sa.DateTime(), nullable=True),
    sa.Column('rosstat_id', sa.Integer(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('date_last_crawl', sa.DateTime(), nullable=True),
    sa.Column('city_code', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nu_rtpipricepage_id'), 'nu_rtpipricepage', ['id'], unique=False)
    op.create_index(op.f('ix_nu_rtpipricepage_web_price_id'), 'nu_rtpipricepage', ['web_price_id'], unique=False)
    op.create_table('nu_rtpiproductname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('moment', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nu_rtpiproductname_id'), 'nu_rtpiproductname', ['id'], unique=False)
    op.create_index(op.f('ix_nu_rtpiproductname_web_price_id'), 'nu_rtpiproductname', ['web_price_id'], unique=False)
    op.create_table('nu_rtpistoreid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('store_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nu_rtpistoreid_id'), 'nu_rtpistoreid', ['id'], unique=False)
    op.create_index(op.f('ix_nu_rtpistoreid_store_id'), 'nu_rtpistoreid', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nu_rtpistoreid_store_id'), table_name='nu_rtpistoreid')
    op.drop_index(op.f('ix_nu_rtpistoreid_id'), table_name='nu_rtpistoreid')
    op.drop_table('nu_rtpistoreid')
    op.drop_index(op.f('ix_nu_rtpiproductname_web_price_id'), table_name='nu_rtpiproductname')
    op.drop_index(op.f('ix_nu_rtpiproductname_id'), table_name='nu_rtpiproductname')
    op.drop_table('nu_rtpiproductname')
    op.drop_index(op.f('ix_nu_rtpipricepage_web_price_id'), table_name='nu_rtpipricepage')
    op.drop_index(op.f('ix_nu_rtpipricepage_id'), table_name='nu_rtpipricepage')
    op.drop_table('nu_rtpipricepage')
    op.drop_index(op.f('ix_nu_rtpiprice_web_price_id'), table_name='nu_rtpiprice')
    op.drop_index(op.f('ix_nu_rtpiprice_stock_status'), table_name='nu_rtpiprice')
    op.drop_index(op.f('ix_nu_rtpiprice_id'), table_name='nu_rtpiprice')
    op.drop_table('nu_rtpiprice')
    # ### end Alembic commands ###
