"""Initial migration

Revision ID: 9ca2b8559232
Revises: 
Create Date: 2022-08-18 01:41:29.954922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca2b8559232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rtpiprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('date_observe', sa.DateTime(), nullable=True),
    sa.Column('stock_status', sa.Text(), nullable=True),
    sa.Column('current_price', sa.BigInteger(), nullable=True),
    sa.Column('crossed_price', sa.BigInteger(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_price_id', 'date_observe', name='web_price_id_date_observe_unique')
    )
    op.create_index(op.f('ix_rtpiprice_id'), 'rtpiprice', ['id'], unique=False)
    op.create_index(op.f('ix_rtpiprice_stock_status'), 'rtpiprice', ['stock_status'], unique=False)
    op.create_index(op.f('ix_rtpiprice_web_price_id'), 'rtpiprice', ['web_price_id'], unique=False)
    op.create_table('rtpipricepage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('price_name', sa.Text(), nullable=True),
    sa.Column('price_url', sa.Text(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.Column('date_last_in_stock', sa.DateTime(), nullable=True),
    sa.Column('rosstat_id', sa.Integer(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('date_last_crawl', sa.DateTime(), nullable=True),
    sa.Column('city_code', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_price_id', name='web_price_id_unique')
    )
    op.create_index(op.f('ix_rtpipricepage_id'), 'rtpipricepage', ['id'], unique=False)
    op.create_index(op.f('ix_rtpipricepage_web_price_id'), 'rtpipricepage', ['web_price_id'], unique=False)
    op.create_table('rtpiproductname',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_price_id', sa.BigInteger(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('moment', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_price_id', 'product_name', name='web_price_id_product_name_unique')
    )
    op.create_index(op.f('ix_rtpiproductname_id'), 'rtpiproductname', ['id'], unique=False)
    op.create_index(op.f('ix_rtpiproductname_web_price_id'), 'rtpiproductname', ['web_price_id'], unique=False)
    op.create_table('rtpistoreid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('store_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_name', name='store_name_unique')
    )
    op.create_index(op.f('ix_rtpistoreid_id'), 'rtpistoreid', ['id'], unique=False)
    op.create_index(op.f('ix_rtpistoreid_store_id'), 'rtpistoreid', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rtpistoreid_store_id'), table_name='rtpistoreid')
    op.drop_index(op.f('ix_rtpistoreid_id'), table_name='rtpistoreid')
    op.drop_table('rtpistoreid')
    op.drop_index(op.f('ix_rtpiproductname_web_price_id'), table_name='rtpiproductname')
    op.drop_index(op.f('ix_rtpiproductname_id'), table_name='rtpiproductname')
    op.drop_table('rtpiproductname')
    op.drop_index(op.f('ix_rtpipricepage_web_price_id'), table_name='rtpipricepage')
    op.drop_index(op.f('ix_rtpipricepage_id'), table_name='rtpipricepage')
    op.drop_table('rtpipricepage')
    op.drop_index(op.f('ix_rtpiprice_web_price_id'), table_name='rtpiprice')
    op.drop_index(op.f('ix_rtpiprice_stock_status'), table_name='rtpiprice')
    op.drop_index(op.f('ix_rtpiprice_id'), table_name='rtpiprice')
    op.drop_table('rtpiprice')
    # ### end Alembic commands ###
