"""job persistance

Revision ID: a7750480c429
Revises: 9ca2b8559232
Create Date: 2022-08-28 22:11:41.029249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7750480c429'
down_revision = '9ca2b8559232'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('func', sa.String(), nullable=True),
    sa.Column('args', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('kwargs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('time_started', sa.DateTime(), nullable=True),
    sa.Column('time_completed', sa.DateTime(), nullable=True),
    sa.Column('parent_job_id', sa.String(length=191), nullable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
